# Generated by Django 5.2.4 on 2025-07-12 19:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goal",
            options={
                "ordering": ["-priority", "deadline", "-created_at"],
                "verbose_name": "هدف",
                "verbose_name_plural": "اهداف",
            },
        ),
        migrations.AlterField(
            model_name="goal",
            name="category",
            field=models.CharField(
                choices=[
                    ("relationship", "رابطه"),
                    ("financial", "مالی"),
                    ("health", "سلامتی"),
                    ("travel", "سفر"),
                    ("home", "خانه"),
                    ("personal", "شخصی"),
                    ("other", "سایر"),
                ],
                max_length=20,
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="تکمیل شده"),
        ),
        migrations.AlterField(
            model_name="goal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="goal",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_goals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ایجاد شده توسط",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="deadline",
            field=models.DateField(blank=True, null=True, verbose_name="مهلت"),
        ),
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="goal",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "کم"), (2, "متوسط"), (3, "زیاد")],
                default=2,
                verbose_name="اولویت",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="progress",
            field=models.IntegerField(
                default=0,
                help_text="درصد پیشرفت از 0 تا 100",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="پیشرفت",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title",
            field=models.CharField(max_length=200, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="goal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
    ]
