# Generated by Django 5.2.4 on 2025-07-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_alter_completedactivity_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="", verbose_name="Active"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="points",
            field=models.PositiveIntegerField(help_text="", verbose_name="Points"),
        ),
    ]
