# Generated by Django 5.2.4 on 2025-07-12 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memory",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "خاطره",
                "verbose_name_plural": "خاطرات",
            },
        ),
        migrations.AlterField(
            model_name="memory",
            name="content",
            field=models.TextField(verbose_name="متن خاطره"),
        ),
        migrations.AlterField(
            model_name="memory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="memory",
            name="date",
            field=models.DateField(verbose_name="تاریخ"),
        ),
        migrations.AlterField(
            model_name="memory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="memories/", verbose_name="تصویر"
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="مکان"
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="mood",
            field=models.CharField(
                choices=[
                    ("happy", "شاد"),
                    ("love", "عاشقانه"),
                    ("excited", "هیجان\u200cزده"),
                    ("relaxed", "آرام"),
                    ("content", "راضی"),
                    ("sad", "غمگین"),
                    ("angry", "عصبانی"),
                    ("neutral", "خنثی"),
                ],
                default="content",
                max_length=20,
                verbose_name="حس و حال",
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="title",
            field=models.CharField(max_length=200, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="memory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="memory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
