# Generated by Django 5.2.4 on 2025-07-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0002_alter_memory_options_alter_memory_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="این فیلد برای سازگاری با نسخه\u200cهای قبلی حفظ شده است. لطفاً از قابلیت آپلود چند تصویر استفاده کنید.",
                null=True,
                upload_to="memories/",
                verbose_name="تصویر (قدیمی)",
            ),
        ),
        migrations.CreateModel(
            name="MemoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="memories/", verbose_name="تصویر"),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="توضیح تصویر",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "memory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="memories.memory",
                        verbose_name="خاطره",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر خاطره",
                "verbose_name_plural": "تصاویر خاطرات",
                "ordering": ["order", "id"],
            },
        ),
    ]
