# Generated by Django 5.2.4 on 2025-07-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0003_alter_memory_image_memoryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="mood",
            field=models.CharField(
                choices=[
                    ("happy", "شاد"),
                    ("love", "عاشقانه"),
                    ("excited", "هیجان\u200cزده"),
                    ("relaxed", "آرام"),
                    ("content", "راضی"),
                    ("sad", "غمگین"),
                    ("angry", "عصبانی"),
                    ("neutral", "خنثی"),
                    ("surprised", "متعجب"),
                    ("laughing", "خندان"),
                    ("cool", "باحال"),
                    ("silly", "شوخ"),
                    ("thinking", "متفکر"),
                ],
                default="content",
                max_length=20,
                verbose_name="حس و حال",
            ),
        ),
    ]
