# Generated by Django 5.2.4 on 2025-07-12 11:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date")),
                (
                    "mood_type",
                    models.CharField(
                        choices=[
                            ("very_happy", "Very Happy"),
                            ("happy", "Happy"),
                            ("content", "Content"),
                            ("neutral", "Neutral"),
                            ("sad", "Sad"),
                            ("frustrated", "Frustrated"),
                            ("angry", "Angry"),
                            ("very_sad", "Very Sad"),
                        ],
                        max_length=20,
                        verbose_name="Mood Type",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rate your mood from 1 (worst) to 10 (best)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mood",
                "verbose_name_plural": "Moods",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
