# Generated by Django 5.2.4 on 2025-07-12 19:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mood",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "حال و هوا",
                "verbose_name_plural": "حال و هوا",
            },
        ),
        migrations.AlterField(
            model_name="mood",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="mood",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="تاریخ"),
        ),
        migrations.AlterField(
            model_name="mood",
            name="mood_type",
            field=models.CharField(
                choices=[
                    ("very_happy", "بسیار خوشحال"),
                    ("happy", "خوشحال"),
                    ("content", "راضی"),
                    ("neutral", "معمولی"),
                    ("sad", "غمگین"),
                    ("frustrated", "کلافه"),
                    ("angry", "عصبانی"),
                    ("very_sad", "بسیار غمگین"),
                ],
                max_length=20,
                verbose_name="نوع حال و هوا",
            ),
        ),
        migrations.AlterField(
            model_name="mood",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="یادداشت\u200cها"
            ),
        ),
        migrations.AlterField(
            model_name="mood",
            name="rating",
            field=models.IntegerField(
                help_text="حال و هوای خود را از 1 (بدترین) تا 10 (بهترین) امتیاز دهید",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="امتیاز",
            ),
        ),
        migrations.AlterField(
            model_name="mood",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
