# Generated by Django 5.2.4 on 2025-07-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moods", "0002_alter_mood_options_alter_mood_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mood",
            name="mood_type",
            field=models.CharField(
                choices=[
                    ("very_happy", "بسیار خوشحال"),
                    ("happy", "خوشحال"),
                    ("excited", "هیجان\u200cزده"),
                    ("content", "راضی"),
                    ("relaxed", "آرام"),
                    ("neutral", "معمولی"),
                    ("confused", "سردرگم"),
                    ("anxious", "مضطرب"),
                    ("sad", "غمگین"),
                    ("frustrated", "کلافه"),
                    ("angry", "عصبانی"),
                    ("sleepy", "خواب\u200cآلود"),
                    ("very_sad", "بسیار غمگین"),
                ],
                max_length=20,
                verbose_name="نوع حال و هوا",
            ),
        ),
    ]
