# Generated by Django 5.2.4 on 2025-07-14 20:32

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=280,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="متن یادداشت"
                    ),
                ),
                (
                    "snippet",
                    models.TextField(
                        blank=True,
                        help_text="خلاصه\u200cای کوتاه از یادداشت",
                        verbose_name="خلاصه",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشر شده"),
                            ("archived", "بایگانی شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "کم"),
                            (2, "متوسط"),
                            (3, "زیاد"),
                            (4, "بسیار زیاد"),
                        ],
                        default=2,
                        verbose_name="اولویت",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="سنجاق شده"),
                ),
                (
                    "reminder_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="یادآوری"),
                ),
                (
                    "is_reminded",
                    models.BooleanField(default=False, verbose_name="یادآوری شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "یادداشت",
                "verbose_name_plural": "یادداشت\u200cها",
                "ordering": ["-is_pinned", "-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="notes/attachments/%Y/%m/", verbose_name="فایل"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام فایل")),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نوع فایل"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        default=0, help_text="حجم به بایت", verbose_name="حجم فایل"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ آپلود"),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="notes.note",
                        verbose_name="یادداشت",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیوست یادداشت",
                "verbose_name_plural": "پیوست\u200cهای یادداشت",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام دسته\u200cبندی"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=120,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="کلاس Font Awesome مانند fa-book",
                        max_length=50,
                        verbose_name="آیکون",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="کد رنگ مانند #FF4081",
                        max_length=20,
                        verbose_name="رنگ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی یادداشت",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای یادداشت",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="note",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="notes.notecategory",
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام برچسب")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=70,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="کد رنگ مانند #FF4081",
                        max_length=20,
                        verbose_name="رنگ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "برچسب",
                "verbose_name_plural": "برچسب\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="notes",
                to="notes.tag",
                verbose_name="برچسب\u200cها",
            ),
        ),
    ]
