# Generated by Django 5.2.4 on 2025-07-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0002_alter_reward_options_alter_rewardcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="cost",
            field=models.PositiveIntegerField(
                default=0, verbose_name="امتیاز مورد نیاز"
            ),
        ),
    ]
