# Generated by Django 5.2.4 on 2025-07-12 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0003_reward_cost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reward",
            options={
                "ordering": ["cost"],
                "verbose_name": "قالب جایزه",
                "verbose_name_plural": "قالب\u200cهای جوایز",
            },
        ),
        migrations.RemoveField(
            model_name="reward",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="reward",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="reward",
            name="status",
        ),
        migrations.RemoveField(
            model_name="reward",
            name="used_at",
        ),
        migrations.AddField(
            model_name="reward",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="فقط جوایز فعال در فروشگاه نمایش داده می\u200cشوند.",
                verbose_name="فعال",
            ),
        ),
        migrations.CreateModel(
            name="RedeemedReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ دریافت"
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="rewards.reward",
                        verbose_name="جایزه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redeemed_rewards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "جایزه دریافت شده",
                "verbose_name_plural": "جوایز دریافت شده",
                "ordering": ["-redeemed_at"],
            },
        ),
    ]
