# Generated by Django 5.2.4 on 2025-07-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0004_alter_reward_options_remove_reward_creator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reward",
            name="category",
        ),
        migrations.DeleteModel(
            name="RewardCategory",
        ),
    ]
